"""Add created_at timestamp

Revision ID: 27a5bdd5601b
Revises: fcb8ec4de5fc
Create Date: 2026-02-08 18:05:46.637453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a5bdd5601b'
down_revision: Union[str, Sequence[str], None] = 'fcb8ec4de5fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column with server_default to handle existing rows
    op.add_column('seashell', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seashell', 'created_at')
    # ### end Alembic commands ###
