"""Initial schema

Revision ID: fcb8ec4de5fc
Revises: 
Create Date: 2026-02-08 18:04:42.997692

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'fcb8ec4de5fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
